Making doker_pull compatible with python3
NotGlop/docker-drag pull request #3
Opened 2019-07-10 19:47 UTC by jeffque

The major changes were:

- `print` as a function
- module `io` contains `StringIO`, not `StringIO` anymore
- treat bytes stuff like bytes (such as `BytesIO` and `wb` as file-mode to open the proper file)
- encode 'utf-8' string when needed (aka line 68)

2019-07-10 20:28 UTC, jeffque commented
So, when I testes this I got a seg fault... don't know why nor in which line

2019-08-19 12:51 UTC, NotGlop commented
Thank you for the update. 
Did you fix the seg fault or do you still have the issue? 

Few remarks:
Line 49: should be not be treated as bytes (it is a plain text json config file) 
Line 68: why do you want to UTF8 encode the sha256 hash?

Other modifications are alright for me.

2019-08-19 13:23 UTC, NotGlop requested changes
Will approve but please clean and fix this.

Line 4: remove the now unneeded StringIO
Line 78: replace it with `sys.stdout.write(ublob[7:19] + ': Downloading...')`
Line 79: remove the extra ')' at the end of the line

Thank you

2019-08-20 19:43 UTC, jeffque commented
Requested changes commited

> Did you fix the seg fault or do you still have the issue?

Unfortunatly, I still has no idea where this seg fault came in and also have not tested yet (yep, commited blindly)

2019-08-20 21:41 UTC, NotGlop approved these changes
Supporting Python3:
- modifying print functions
- treating data as bytes

2019-08-20 22:29 UTC, merged